Interacting With Chargers, initial commit.
toasted-marshmallow-co/DarkWarehouse.PublicDocs pull request #42
Opened 2024-03-07 05:18 UTC by DLthaIII

2024-03-08 06:48 UTC, DLthaIII commented
![pr-screenshot](https://github.com/toasted-marshmallow-co/DarkWarehouse.PublicDocs/assets/64317582/c1ec4515-d219-4225-8a92-52bc433438ac)

2024-03-08 14:23 UTC, itstudes requested changes
The documentation looks decent, but please let me know once you've addressed the comments then we'll merge

2024-03-08 14:23 UTC, itstudes commented on docs/06-The Equipment/07-Chargers/Interacting with Chargers.md
> +Users can communicate with chargers in two ways: directly interacting with chargers (standalone) or indirectly using machines (remotely controlled)📡. Chargers can be identified within the system by t
This line about users communicating with chargers is factually incorrect. The "standalone" vs "remotely controlled" refers to how the charger itself is controlled. In some cases, the charger will have its own control cabinet, in that case it is "standalone". In other cases something like a VTU/conveyor will control the charger. In those cases it is "remotely controlled".

2024-03-08 14:23 UTC, itstudes commented on docs/06-The Equipment/07-Chargers/Interacting with Chargers.md
> +![charge pad icon](assets/interacting-with-chargers/charge-pad-icon.PNG "charge pad icon").
Is there a reason why this icon is highlighted with a yellow background? Also, could we not show a full screen view and then alongside that, illustrate a zoomed in section showing this?

2024-03-08 14:23 UTC, itstudes commented on docs/06-The Equipment/07-Chargers/Interacting with Chargers.md
> +## Navigate To Toolbox 🔎
Is there a "right-click" mechanism to work with chargers? I think there was on the old view. It'll be good to capture that within these docs too.

2024-03-08 14:23 UTC, itstudes commented on docs/06-The Equipment/07-Chargers/Interacting with Chargers.md
> +The user can immediately click the **Next** button to continue as the destination location is not needed⏩.
Elaborate on why the destination is not needed. In this case it is because the TMS selects the nearest available charger for the selected OM. I think there is also the option to specify a charger, but you'll have to confirm that with Angelica.

2024-03-08 14:23 UTC, itstudes commented on docs/06-The Equipment/07-Chargers/Interacting with Chargers.md
> +## Using Charge Pads
There's definitely some weirdness with heading hierarchy in this section. I would arrange the page such that we have:

## Using Charge Pads

### Sending Omni-Moles to Charge via the LHS Toolbox Menu

### Sending Omni-Moles to Charge via the Right Click Context Menu

### Getting Omni-Moles off Charge Pads

2024-03-08 14:23 UTC, itstudes commented on docs/06-The Equipment/07-Chargers/Interacting with Chargers.md
> +## States Of Charge 🚦
All the different states of charge are settable, so please emphasise that. In the content below it seems as if these are hard-coded values and they are not. These are just the default values.

2024-03-08 14:23 UTC, itstudes commented on docs/06-The Equipment/07-Chargers/Interacting with Chargers.md
> +## States Of Charge 🚦
Also, these are the settings for charging within the app. I would suggest rather naming the section that and not "States of Charge".

2024-03-19 11:41 UTC, itstudes approved these changes
It's looking a lot better; I just have a few minor comments for you to address. Once you've sorted those, you're welcome to merge the branch in!

2024-03-25 08:03 UTC, itstudes approved these changes
After addressing these comments you're welcome to complete this PR

2024-03-25 08:03 UTC, itstudes commented on docs/06-The Equipment/07-Chargers/Interacting with Chargers.md
> +The system offers customizable charge settings that allow users to define the parameters for the Omni-Mole battery🎚️. These settings supply users with information in knowing at what state all Omni-Mo
Perhaps discuss in a bit more depth what these settings do. I'm going to explain but please don't use my exact wording.

The first 4 settings, **Must Go To Charger**, **Can Go To Charger**, **Can Leave Charger** and **Full Cycle Cutoff** are for the daily charging requirements. Basically defining when machines should charge and when they should leave chargers.

The next 2 settings, **Perform Full Charge Cycle Interval Min/Max** are required because the battery is required to undergo a full charge cycle every once in a while. Doing this prolongs the battery's operational life.

2024-03-25 08:03 UTC, itstudes commented on docs/06-The Equipment/07-Chargers/Interacting with Chargers.md
> +- **Can Go To Charger**: If an Omni-Mole reports a charge percentage value of 40% or lower, indicates that the Omni-Mole is is permitted to proceed to a charge pad. At this threshold, the Omni-Mole h
Please also call these settings **Can Leave Charger SoC %**, **Full Cycle Cutoff SoC %**, etc.

Then just after the introductory paragraph please include a :::note section, something like:

:::note
SoC % refers to the state of charge percentage of the battery. Similar to how a mobile phone informs you the battery percentage. The SoC % defines this for the Omni-Mole batteries.
:::

2024-03-25 13:24 UTC, merged